---
title: "Threats to validity"
date: "2022-10-03"
---

## Instructions

You need to complete the ["Assessing validity" section below](/assignment/04-eval-threats.qmd#assessing-validity-1). Ideally you should type this in R Markdown and knit your document to HTML or Word or PDF, but you can also write in Word if you want (though your final project will need to be in R Markdown, and this would give you practice).

**I've created an R Markdown template you can use here:** [{{< fa file-archive >}} `threats-validity.zip`](/projects/threats-validity.zip). It's also [available on RStudio.cloud](https://rstudio.cloud/spaces/269500/content/4357671).

**Submit this assignment as a PDF or Word file on iCollege.**

---

## Internal validity scores

One helpful way to assess an evaluation's internal validity is to systematically go through each possible threat and evaluate if the research design addresses it. For each of the 13 types of internal validity that we discussed in class, assign 1 point if the study addresses it and 0 points if it fails to do so. Add up the total points and assign the study a final internal validity score.

Not all types of validity will apply to every study. Testing, for example, is only an issue if there is a pre-test and it involves a skill that could feasibly be enhanced by practicing the test. If a threat doesn't apply, don't give it a score.

- Omitted variable bias
    1. Selection
    2. Attrition
- Trends
    3. Maturation
    4. Secular trends
    5. Seasonality
    6. Testing
    7. Regression to the mean
- Study calibration
    8. Measurement error
    9. Time frame of study
- Contamination
    10. Hawthorne effects
    11. John Henry effects
    12. Spillovers
    13. Intervening events

---

## Assessing validity

Your textbook [*Impact Evaluation in Practice*](https://openknowledge.worldbank.org/handle/10986/25030) is full of short examples of real-world evaluations, experiments, and studies. For this assignment, you will assess the (1) internal validity, (2) external validity, and (3) construct validity for two of the examples from the book. If the summary in the book isn't sufficient, you can skim through the original study for more details. The original studies can be found in the Content section of iCollege.

You will assess **two (2)** of these four studies. Pick whichever two seem the most interesting to you:

1. **The effect of conditional cash transfers on education in Mexico** (Box 4.2, p. 70) 
    - Original study: [@Schultz:2004]
2. **The impact of *Sesame Street* on school readiness** (Box 5.1, p. 91) 
    - Original study: [@KearneyLevine:2015]
3. **The effects of police deployment on crime in Argentina** (Box 7.2, p. 135)
    - Original study: [@Di-TellaSchargrodsky:2004]
4. **Early childhood development and migration in Jamaica** (Box 9.5, p. 170)
    - Original study: [@GertlerHeckmanPinto:2014]

For each of the two studies you choose, do the following:

1. Go through the 13 types of internal validity and describe *in 2–3 sentences* how the study succeeds/fails to address each concern. Calculate a total internal validity score.
2. Describe any threats to external validity and assess how generalizable the findings are. *(≈75 words)*
3. Describe any threats to construct validity and assess if the researchers are measuring the thing they intended to measure. *(≈75 words)*
