---
title: "Organ donations"
output: html_document
---

## Load and clean data

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(broom)
library(fixest)

organ_donations_raw <- read_csv("data/organ_donations.csv")
```

```{r}
# TODO: Make a dataset based on `organ_donations` that only contains California and New Jersey
# TODO: Make a new column called `After` that is TRUE (or 1) if the quarter is Q32011, Q42011, or Q12012 (or if Quarter_num is 4, 5, or 6)
# TODO: Make a new column called `is_california` that is TRUE (or 1) if the state is California

organ_ca_nj <- organ_donations_raw %>% 
  filter(State %in% c("California", "New Jersey")) %>% 
  mutate(After = Quarter %in% c("Q32011", "Q42011", "Q12012"),
         is_california = State == "California")
```


## Simple diff-in-diff

```{r}
# TODO: Using the data for only California and New Jersey, create a plot that shows
# the donation rate over time, colored by state. Add a vertical line at Q22011 (or Quarter_num = 3).
# Determine if the two states' trends are parallel before the change.
ggplot(organ_ca_nj, aes(x = Quarter_Num, y = Rate, color = State)) + 
  geom_vline(xintercept = 3.5) +
  geom_line()
```

```{r}
# TODO: Use group_by() and summarize() to find the average donation rate in
# California and New Jersey before and after the change in California's policy
diffs <- organ_ca_nj %>%
  group_by(After, State) %>%
  summarize(mean_rate = mean(Rate))

before_treatment <- diffs %>%
  filter(After == FALSE, State == "California") %>%
  pull(mean_rate)

before_control <- diffs %>%
  filter(After == FALSE, State == "New Jersey") %>%
  pull(mean_rate)

after_treatment <- diffs %>%
  filter(After == TRUE, State == "California") %>%
  pull(mean_rate)

after_control <- diffs %>%
  filter(After == TRUE, State == "New Jersey") %>%
  pull(mean_rate)

diff_treatment_before_after <- after_treatment - before_treatment
diff_treatment_before_after

diff_control_before_after <- after_control - before_control
diff_control_before_after

diff_diff <- diff_treatment_before_after - diff_control_before_after
diff_diff
```

```{r}
# TODO: Use lm() to calculate the diff-in-diff effect with this model:
model_diff_diff <- lm(Rate ~ is_california + After + (is_california * After), 
                      data = organ_ca_nj)
tidy(model_diff_diff)
```

$$
\begin{aligned}
\text{Donation rate}\ =&\ \beta_0 + \beta_1\ \text{California} + \beta_2\ \text{After Q22011}\ + \\
&\ \beta_3\ (\text{California} \times \text{After Q22011})
\end{aligned}
$$


## Two-way fixed effects

```{r}
# TODO: Create a new dataset based on `organ_donations_raw` 
# TODO: Make a new column called `After` that is TRUE (or 1) if the quarter is Q32011, Q42011, or Q12012 (or if Quarter_num is 4, 5, or 6)
# TODO: Make a new column called `Treated` that is TRUE (or 1) if the state is California and After is TRUE/1

organ <- organ_donations_raw %>% 
  mutate(After = Quarter %in% c("Q32011", "Q42011", "Q12012")) %>% 
  mutate(Treated = State == "California" & After == TRUE)
```

```{r}
# TODO: Use that new data to create a TWFE model like this:
model_twfe <- lm(Rate ~ Treated + State + After, 
                 data = organ)
tidy(model_twfe)

model_twfe_nice <- feols(Rate ~ Treated | State + After,
                         data = organ)
tidy(model_twfe_nice)
```

$$
\text{Donation rate}\ =\ \beta_0 + \beta_1\ \text{Treatment} + \beta_2\ \text{State} + \beta_3\ \text{After}
$$
